---
#- hosts: master
#  become: yes
#  become_method: sudo
#  tags:
#  - helm
#  tasks:

- set_fact:
    env_kc: '{{ proxy_env |default({}) | combine ({"PATH" : "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin"  }) | combine ({"KUBECONFIG" :"/etc/kubernetes/admin.conf"}) }}'
  tags:
  - always

- block:
  - name: 'Download helm binary archive https://get.helm.sh/helm-{{ helm.helm_version }}-linux-{{ HOST_ARCH }}.tar.gz'
    environment: '{{env_kc}}'
    get_url: 
      url: "https://get.helm.sh/helm-{{ helm.helm_version }}-linux-{{ HOST_ARCH }}.tar.gz"
      dest: /tmp/helm-{{ helm.helm_version }}-linux-{{ HOST_ARCH }}.tar.gz
      force: no
      mode: "0755"
    
  - name: unarchive
    unarchive:
      dest: /tmp/
      src: /tmp/helm-{{ helm.helm_version }}-linux-{{ HOST_ARCH }}.tar.gz
      mode: "0755"
      remote_src: yes

  - name: helm - place binary in destination folder
    copy:
      src: /tmp/linux-{{ HOST_ARCH }}/helm
      dest: /usr/local/bin/
      force: yes
      mode: "0755"
    become: yes
    become_user: root

  - name: helm repo remove (before add)
    environment: '{{env_kc}}'
    command: helm repo remove {{ item.name }}
    with_items:
    - '{{ helm.repos | default("") }}'
    when: helm is defined and helm.repos is defined
    ignore_errors: yes

  - name: helm repo add 
    environment: '{{env_kc}}'
    command: helm repo add {{ item.name }} {{ item.url }}
    with_items: 
    - '{{ helm.repos | default("") }}'
    when: helm is defined and helm.repos is defined

  - name: helm repo update #Sometimes initial repo add corrupts the repo and update fixes it.
    environment: '{{env_kc}}'
    command: helm repo update
    when: helm is defined

  tags:
  - helm

