#https://pkg.go.dev/k8s.io/kube-proxy/config/v1alpha1?tab=doc#KubeProxyConfiguration
#check latest api ver here: https://pkg.go.dev/k8s.io/kube-proxy/config/
KubeProxyConfiguration:
  apiVersion: kubeproxy.config.k8s.io/v1alpha1
  # bindAddress: 0.0.0.0
  # clientConnection:
  #   acceptContentTypes: ""
  #   burst: 10
  #   contentType: application/vnd.kubernetes.protobuf
  #   kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  #   qps: 5
  # clusterCIDR: ""
  clusterCIDR: "{{ POD_NETWORK_CIDR }}"
  ##podSubnet -> Calico is now able to autodetect. If calico is used, this can be commented out.
 # Not required: if here is empty it will read from the ClusterConfiguration.
  # configSyncPeriod: 15m0s
  # conntrack:
  #   max: null
  #   maxPerCore: 32768
  #   min: 131072
  #   tcpCloseWaitTimeout: 1h0m0s
  #   tcpEstablishedTimeout: 24h0m0s
  # enableProfiling: false
  # healthzBindAddress: 0.0.0.0:10256
  # hostnameOverride: ""
  # iptables:
  #   masqueradeAll: false
  #   masqueradeBit: 14
  #   minSyncPeriod: 0s
  #   syncPeriod: 30s
  ipvs:
    strictARP: true
  #   excludeCIDRs: null
  #   minSyncPeriod: 0s
  #   scheduler: ""
  #   syncPeriod: 30s
  kind: KubeProxyConfiguration
  # metricsBindAddress: 127.0.0.1:10249
  # mode: ""
  mode: "ipvs"
  ## Leave mode undefined or "" for the default, which usually is the old iptables method
  # nodePortAddresses: null
  # oomScoreAdj: -999
  # portRange: ""
  # resourceContainer: /kube-proxy
  # udpIdleTimeout: 250ms
