---
# - hosts: master
#   become: yes
#   become_method: sudo
#   environment:
#     KUBECONFIG: /etc/kubernetes/admin.conf
#   tags:
#   - reset
#   - node
#   tasks:

- block:
  - name: get all pvcs
    shell: kubectl get --all-namespaces pvc --no-headers -- | awk '{print "--namespace " $1 " pvc/" $2}'
    register: command_results
    ignore_errors: true
    changed_when: false

  - name: delete all pvcs
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
    command: kubectl delete {{ item }}
    ignore_errors: true
    with_items: "{{command_results.stdout_lines}}"

  - name: wait till all pvcs are removed/cleaned
    shell: "kubectl get pvc --no-headers -- || true"
    register: command_result
    until: command_result.stdout == ""
    retries: 10
    delay: 3
    ignore_errors: true
    changed_when: false

  - name: wait till all pvs are removed/cleaned
    shell: "kubectl get pv --no-headers -- || true"
    register: command_result
    until: command_result.stdout == ""
    retries: "{{ RETRIES | default(40) }}"
    delay: 3
    ignore_errors: true
    changed_when: false

  when: storage.delete_pvs is defined and storage.delete_pvs
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  tags:
  - reset
  
